name: golog
description: View custom logger inside app. Works on debug and release mode.
version: 0.1.3
homepage: https://github.com/irfnyas/golog

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: FiraCode
      fonts:
        - asset: packages/golog/fonts/FiraCode.ttf
